# Generated by Django 2.2.12 on 2020-08-03 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_academicobject_achievementmodel_codingskill_interestmodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='academicobject',
            name='gradYear',
            field=models.IntegerField(default=2020),
        ),
    ]
