# Generated by Django 2.2.12 on 2020-08-03 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_academicobject_gradyear'),
    ]

    operations = [
        migrations.AddField(
            model_name='achievementmodel',
            name='details',
            field=models.TextField(null=True),
        ),
    ]
