# Generated by Django 2.2.12 on 2020-08-03 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_auto_20200803_1655'),
    ]

    operations = [
        migrations.AlterField(
            model_name='codingskill',
            name='proficiency',
            field=models.CharField(choices=[('Working Knowledge', 'Working Knowledge'), ('Proficient', 'Proficient'), ('Fluent', 'Fluent')], default='MID', max_length=17),
        ),
    ]
